name: build

on:
  release:
    types: [ released ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install pyoxidizer
      - run: pyoxidizer build
      - uses: actions/upload-artifact@v3
        with:
          name: ioscustomringtones-${{ runner.os }}
          path: target/release/*/ioscustomringtones*
      - if: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ioscustomringtones_${{ runner.os }}${{ runner.os == 'Windows' && '.exe' || '' }}
          file: target/release/*/ioscustomringtones${{ runner.os == 'Windows' && '.exe' || '' }}
      
